### PR TITLE
Simple stack optimization & concatenated codegen

### PR DESCRIPTION
**Pull request by sannysanoff**
This pull requests greatly simplifies stack operations resulting assembly (e.g, i've seen ALOAD taking 2 ARM ops) via little change in method stack implementation.

Also, this pull request contains _option_ to produce concatenated .m files instead of myriads of little C files thus reducing compile time by more than 60% (on my project). (Reason of inclusion of this feature is that it was already included in my commit while cherrypicking)

### CODE REVIEW

**Comment by sannysanoff** [comment]
Benchmarks are in "UPDATE" section of document located at

https://docs.google.com/spreadsheets/u/1/d/1zALNJKvBrvfPTSe9EpsOSsSHDivmacFkIXHFwQd2MM0/pubhtml?gid=1206755131&single=true

**Comment by codenameone** [comment]
Hi, 
thanks for this. It looks very interesting and we want to merge this. I have a couple of questions/comments first though:

1. Can you add license headers to the new files? Please base them on our license headers.

2. ConcatenatingFileOutputSteeam is misspelled (should be ConcatenatingFileOutputStream) but I don't quite understand what you are doing there? 
Are you generating one HUGE file of all the class files? For what purpose?

3. Is this necessary: https://github.com/sannysanoff/CodenameOne/commit/6541ae66d6ece06d02c980055af6bf3910b4aa30 ?
Based on your comment it didn't affect performance so I would guess its not. It seems like a huge change which includes risk and we'd rather avoid risk if its not essential.

4. Looking at the number columns in the chart it seems that release is performing slower than debug or am I misreading the data?

Thanks!

**Comment by sannysanoff** [comment]
1) done
2) For the purpose of speeding up the compiler. It causes my project to take 2:50 instead of 6:30 in xcode to compile.
3) i am not sure which part of commit you're talking about. 
4) yes; I'm using xcode 7.2.1, I use project as it is generated, I press "debug on device" button, it uploads binary to device; then I detach debug session and launch same app in springboard. I hoped release builds will improve even more, but it didn't. I'll investigate and post more on the comment, maybe there's some unexpected xcode behavior or combination in clang flags.

**Comment by sannysanoff** [comment]
Re "4)".
I observe with my own eyes (restarted xcode): Pressing "edit scheme" in xcode, seeing "Run" setting: "Debug" configuration is specified for it, but when pressing "Run", build is in progress and -Ofast is sent to compiler, although Debug configuration in project settings explicitly contains "-O0". 

Xcode sucks, because it complicates all so much. Obviously, there's a cause for this behavior, but i give up.

**Comment by codenameone** [comment]
I was referring to the commits marked as "trying to approach..... nothing works yet."

Specifically changing `stack[stackPointer]` to `*SP`.

**Comment by sannysanoff** [comment]
Ok, my xcode specified -O0 on the project level, but -Ofast on target level, so that was the cause. Regenerating project while it's open in xcode does not re-load that option (although normally xcode detects project changes and reloads it silently). So I'll update the spreadsheet.

----

changing stack[stackPointer] to *SP is the core of the patch. 

"stack[stackPointer + 3] = 77" translates to (unoptimized code, destination is left operand, x86-like asm)

mov reg, [stack]                        ; load variable "stack"
mov reg2, [stackPointer]           ; load variable "stackPointer"
add reg2, 3
mul reg2, sizeof struct
add reg, reg2                     ; final location
mov [reg], 77                     ; store needed value in stack

"SP[-3] = 77" translates to

mov reg, [SP]                    ; load variable
mov [reg + (3 * sizeof struct)], 77     ; store needed value in stack

so multiplication is removed completely in "SP" version.

**Comment by codenameone** [comment]
Great, thanks!

**Comment by codenameone** [comment]
Issue #1689 seems to be triggered by this. We also ran into some other issues and have currently reverted out servers to use the older version of the translator. I made one change trying to fix these issues but so far unsuccessfully.

**Comment by JrmyDev** [comment]
I can't build anymore for iOS since 24/02/2016 (10H00 GMT+1). ... Maybe it's link with this !! It's seems the command (and '-DconcatenateFiles' parameter) is misinterpreted by the compiler :
 `java -DconcatenateFiles false ...` & `could not find or load main class false`

FYI, builds have succeeded until 23/02/2016 17H54 GMT+1 
It might be related with server/github modifications 

Thanks.

img_0001

**Comment by codenameone** [comment]
That's unrelated to this issue and should be resolved now.

**Comment by JrmyDev** [comment]
It's ok, thanks.

**Comment by shai-almog** [comment]
@all-contributors please add @sannysanoff  for code

**Comment by sannysanoff** [comment]
Cheers!

**Pull request merged**
