### PR TITLE
Change LocationManager priority will start working now

### PR DESCRIPTION
**Pull request by Adalbert393**
Now req parameter will be used in bindListener() and than in startUpdatingLocation. Without this commit it req parameter change nothing.

### CODE REVIEW

**Comment by codenameone** [comment]
I'm guessing this will collide with this code:

````java
    public void setLocationListener(final LocationListener l) {
        synchronized (this) {
            if (listener != null) {
                clearListener();
                request = null;
                status = TEMPORARILY_UNAVAILABLE;
            }
````

**Comment by Adalbert393** [comment]
Yes, you're right furthermore getCurrentLocation() do not create listener so it prevent to execute clearListner(). Now I test another solution if it will be ok I create enother pull request, so you can close this pull request.

**Comment by Adalbert393** [comment]
Second commit fix the problem of changing LocationManager priority

**Comment by codenameone** [comment]
Thanks!

**Comment by codenameone** [comment]
I've had to revert this as I got reports that basic location listener functionality stopped working after this change.

**Comment by Adalbert393** [comment]
What do you mean "basic location listener functionality stopped working"? I use location listener and it is working without any problem. Maybe there is problem with proper setup LocationRequest?
For sure changing priority in Location Request is not working without this change. Every time default priority (100m accuracy) is setup.

**Comment by Adalbert393** [comment]
So on simulator listener fails because an exception in StubLocationManager.java cleanListener() (Null exception) skip listener initialisation - goto catch block. But on iOS we need to cleanListener even listener and task is not started because getCurrentLocation in IOSImplementation.java use bindListener. So for now I propose check if task or timer is null in StubLocationManager.java cleanListener() becuase iOS implementation is quite complex and I am not sure if this bindListener is needed.

**Comment by Adalbert393** [comment]
I think you need to open the pull request to get last commit?

**Comment by codenameone** [comment]
There was a problem with set resulting in a null value after the fact. I don't see a way to re-open this PR now I think we'll need something new but I also think we need way better testing as this code seems to be very sensitive to changes of this sort. I doubt most of these changes can be covered in the unit tests of the project though.

**Comment by shai-almog** [comment]
@all-contributors please add @Adalbert393  for code

**Pull request merged**
