### PR TITLE
Fix Sockets implementation

### PR DESCRIPTION
**Pull request by ddyer0**
Fix 2 problems with the sockets implementation, infinite error loop waiting for input,
and data corruption problem.

### CODE REVIEW

**Comment by codenameone** [comment]
I think you accidentally merged content from the "LookAndFeelRefactoring" branch into the master branch. This is a bit problematic since we don't yet want to commit this into the master. 

I tried using gits cherry pick to keep your identity on the commit but it doesn't seem to work for pull requests, @shannah  do you know how we can only merge the changes to Sockets.java?

**Comment by shannah** [comment]
I merged only commit ab4db93.  That looks like the only one pertaining to Sockets.

**Comment by codenameone** [comment]
For the record, how do you do something like that?

**Comment by shannah** [comment]
This post shows some decent instructions.
http://mispdev.blogspot.ca/2013/02/github-cherry-picking-commits-from-pull.html

**Comment by codenameone** [comment]
I did cherry pick and got this:

    $ git cherry-pick ab4db935c020ae1432819d3fabf313aebfc0e69d
    fatal: bad object ab4db935c020ae1432819d3fabf313aebfc0e69d

**Comment by shannah** [comment]
I just used the short commit ID.  Maybe it doesn't like long IDs.  Here is the full readout of the process from Terminal.

~~~~
Steves-iMac:CodenameOne-git shannah$ git checkout -b dyer_master master
M	.gitignore
M	Ports/J2ME/nbproject/build-impl.xml
M	Ports/J2ME/nbproject/genfiles.properties
M	Ports/iOSPort/nbproject/private/private.properties
M	vm/ByteCodeTranslator/nbproject/project.properties
Switched to a new branch 'dyer_master'
Steves-iMac:CodenameOne-git shannah$ git pull https://github.com/ddyer0/CodenameOne.git master
remote: Counting objects: 239, done.
remote: Total 239 (delta 164), reused 164 (delta 164), pack-reused 75
Receiving objects: 100% (239/239), 52.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (175/175), completed with 75 local objects.
From https://github.com/ddyer0/CodenameOne
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	vm/ByteCodeTranslator/nbproject/project.properties
Please, commit your changes or stash them before you can merge.
Aborting
Steves-iMac:CodenameOne-git shannah$ git branch
  Version-3.0
  background-exec
* dyer_master
  facebook-invite
  ios_keyboard_fixes
  issue_1372
  issue_1484
  js-port-changes
  local_config
  master
  optimize_bytecode_translator
  revert-1580-master
  tileImage
Steves-iMac:CodenameOne-git shannah$ git stash save
Saved working directory and index state WIP on dyer_master: 65f24a1 Merge branch 'master' of https://github.com/codenameone/CodenameOne
HEAD is now at 65f24a1 Merge branch 'master' of https://github.com/codenameone/CodenameOne
Steves-iMac:CodenameOne-git shannah$ git pull https://github.com/ddyer0/CodenameOne.git master
From https://github.com/ddyer0/CodenameOne
 * branch            master     -> FETCH_HEAD
Auto-merging CodenameOne/src/com/codename1/ui/Display.java
Auto-merging CodenameOne/src/com/codename1/ui/Container.java
Merge made by the 'recursive' strategy.
 .../codename1/impl/CodenameOneImplementation.java  | 635 +++++++++++++-
 CodenameOne/src/com/codename1/io/Socket.java       | 118 ++-
 .../src/com/codename1/ui/BrowserComponent.java     |  42 +-
 CodenameOne/src/com/codename1/ui/Button.java       |   7 -
 CodenameOne/src/com/codename1/ui/Component.java    | 232 +----
 CodenameOne/src/com/codename1/ui/Container.java    |   6 +-
 CodenameOne/src/com/codename1/ui/Display.java      |   2 +-
 CodenameOne/src/com/codename1/ui/EncodedImage.java |   8 +-
 CodenameOne/src/com/codename1/ui/Font.java         |  61 +-
 CodenameOne/src/com/codename1/ui/FontImage.java    |   8 +
 CodenameOne/src/com/codename1/ui/Form.java         |   8 +-
 CodenameOne/src/com/codename1/ui/Graphics.java     |  58 +-
 CodenameOne/src/com/codename1/ui/Image.java        |  89 +-
 CodenameOne/src/com/codename1/ui/IndexedImage.java |   8 +
 CodenameOne/src/com/codename1/ui/Label.java        |  50 +-
 .../src/com/codename1/ui/PeerComponent.java        |   2 +-
 CodenameOne/src/com/codename1/ui/RGBImage.java     |   8 +
 CodenameOne/src/com/codename1/ui/TextArea.java     |   2 +-
 CodenameOne/src/com/codename1/ui/TextField.java    |   2 +-
 CodenameOne/src/com/codename1/ui/Transform.java    |  18 +-
 .../src/com/codename1/ui/animations/Timeline.java  |   8 +
 .../com/codename1/ui/plaf/DefaultLookAndFeel.java  |   4 +
 .../src/com/codename1/ui/plaf/LookAndFeel.java     |   4 +
 CodenameOne/src/com/codename1/ui/plaf/Style.java   |  69 ++
 .../codename1/impl/android/AndroidAsyncView.java   |  89 +-
 .../codename1/impl/android/AndroidGraphics.java    | 687 ++++++++++++++-
 .../impl/android/AndroidImplementation.java        |  67 +-
 .../impl/android/CodenameOneTextPaint.java         |  50 ++
 Ports/iOSPort/nativeSources/IOSNative.m            | 562 ++++++++++++
 .../com/codename1/impl/ios/IOSImplementation.java  |  12 +
 vm/ByteCodeTranslator/nbproject/build-impl.xml     |  89 +-
 vm/ByteCodeTranslator/nbproject/build-native.xml~  | 951 +++++++++++++++++++++
 .../nbproject/genfiles.properties                  |   6 +-
 vm/ByteCodeTranslator/nbproject/project.properties |   3 +-
 vm/ByteCodeTranslator/nbproject/project.xml        |   1 -
 vm/JavaAPI/src/java/lang/Throwable.java            |  12 +-
 36 files changed, 3463 insertions(+), 515 deletions(-)
 create mode 100644 Ports/Android/src/com/codename1/impl/android/CodenameOneTextPaint.java
 create mode 100644 vm/ByteCodeTranslator/nbproject/build-native.xml~
Steves-iMac:CodenameOne-git shannah$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Steves-iMac:CodenameOne-git shannah$ git cherry-pick ab4db93
[master 2c006a4] Fix 2 problems with Sockets; data corruption and infinite error loop when input socket is closed.
 Author: ddyer0 <ddyer-github@real-me.net>
 Date: Mon Dec 28 14:36:40 2015 -0800
 1 file changed, 79 insertions(+), 39 deletions(-)
Steves-iMac:CodenameOne-git shannah$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.DS_Store
	.redcar/
	build.xml
	build_ios_tools.sh
	build_javase_tools.sh

nothing added to commit but untracked files present (use "git add" to track)
Steves-iMac:CodenameOne-git shannah$ git log
commit 2c006a4d1b0125915a92f41155a20b41d1b4e25b
Author: ddyer0 <ddyer-github@real-me.net>
Date:   Mon Dec 28 14:36:40 2015 -0800

    Fix 2 problems with Sockets; data corruption and infinite error loop when input socket is closed.
    
    When the input stream was closed while waiting for data, an infinite
    loop of errors occurred, and the caller waits forever.   When the input
    buffer emptied, 1 character of input could be lost when retrieving the
    next buffer of data.

commit 65f24a148b5f702d3834963a40fa0f45db8acc21
Merge: 8ace3f7 0513d20
Author: Steve Hannah <steve@weblite.ca>
Date:   Tue Dec 29 16:49:07 2015 -0800

    Merge branch 'master' of https://github.com/codenameone/CodenameOne

commit 8ace3f7248f0484376e37641e2304dc5437567b9
Author: Steve Hannah <steve@weblite.ca>
Date:   Tue Dec 29 16:49:02 2015 -0800

Steves-iMac:CodenameOne-git shannah$ git push origin master
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (8/8), 1.99 KiB | 0 bytes/s, done.
Total 8 (delta 5), reused 2 (delta 2)
To https://github.com/codenameone/CodenameOne.git
   65f24a1..2c006a4  master -> master
~~~~

**Pull request closed without merging**
