### PR TITLE
Issue #3646: Generate Surefire-compatible XML when running tests via Maven

### PR DESCRIPTION
**Pull request by Rocketeer007**
* Fixed `TestRunner` to correctly support the `-junitXML` parameter
* Implemented generation of XML file with test report on completion of a test suite
* Added a `testName` paramter to `TestReporting.testExecutionFinished` as the existing implementation for the test name was generating an NPE
* Changed `JUnitXMLReporting` to also use the default reporting logic (we can see output in Maven logs as well as in generated XML)
* Improved `TestExecuter` so that test exceptions are logged correctly
* Changed `RunTestMojo` to enable `-junitXML` when calling `TestRunner`, and generate a `"cn1-reports"` directory for the output

### CODE REVIEW

**Comment by shai-almog** [comment]
Do you need help understanding the build errors?

https://github.com/codenameone/CodenameOne/actions/runs/3240963162/jobs/5312265710

**Comment by Rocketeer007** [comment]
I have to confess, I'm really confused by those build errors. 

I'm assuming the root cause is that the build job is using an older version of Java than I'm using locally, which doesn't include some of the classes and methods I'm using.  However, the build job specifies Java 8, and I'm using Java 8... and `PrintWriter` has been around since JDK1.1.

I've taken a wild guess, and replaced the wildcard import with explicit imports, and swapped out the more complex uses of `Throwable` to see if that makes a difference...

**Comment by Rocketeer007** [comment]
Okay, seen the new failures, which suggest the build is fine, but the VM is not happy passing around `UnitTest` instances from different classloaders.  This makes sense - one of the changes I had to make was to prevent separate instances of `TestRunner` from being created by each classloader, as otherwise we only got half the information about the tests.

Oddly, actually using the new classes in Maven and in TestRunner did work, so I'm not 100% sure why it fails in the build infrastructure... so the first thing I'm going to do is figure out how to run these tests locally and reproduce the problem.

My proposed solution will be to modify the `TestReporting` API to take the test name as a String, rather than the `UnitTest` object itself - I originally had that as part of this PR, but ended up reverting it as "too wide-reaching".

**Comment by shai-almog** [comment]
This looks good to me. Just one small caveat.  You changed a couple of public method signatures e.g.:

```java
public void testExecutionFinished(String testSuiteName) {
}
```

This might be OK but in theory someone might have subclassed and overriden these APIs. I think the right thing to do here would be something like:


```java
public void testExecutionFinished(String testSuiteName) {
    testExecutionFinished();
}

/**
 * @deprecated Please use #testExecutionFinished(String)
 */
public void testExecutionFinished() {
}
```

Does that make sense?

@shannah what do you think?

**Comment by Rocketeer007** [comment]
Added deprecated methods as you suggest. If anyone has overridden the `startingTestCase` or `endingTestCase` methods, they'll have to make changes to restore functionality to their reporting mechanism, but at least it will still compile, and the deprecation warnings will tell them where to look.

Anyone _using_ CodenameOne should be unaffected, since I can't see any way to successfully inject a different reporting tool while running tests that use this framework (calling `TestReporting.setInstance` during a test would have changed the reporting tool used in that test, but since the tests used a different classloader than the test framework, it would have been quite a mixture of different tools depending on what exceptions occurred and when.

Anyone _extending_ CodenameOne and supplying a new `TestReporting` instance will have to make changes for it to work correctly.

**Comment by shai-almog** [comment]
Great. Thanks for all the hard work!

**Comment by shai-almog** [comment]
@all-contributors please add @Rocketeer007 for code

**Pull request merged**
