### PR TITLE
adding callback to stream copy

### PR DESCRIPTION
**Pull request by kutoman**
it's my proposal to track the stream copy progress which is useful when large files needs to be copied (e.g. when downloading big files and the progress needs to be shown to the app user).

If this gets accepted, I would suggest to also extend the linked copy methods by callback parameters

### CODE REVIEW

**Comment by codenameone** [comment]
Hi,
It's missing the Consumer interface but do you know that Codename One's streams are buffered by default and observable?

https://www.codenameone.com/javadoc/com/codename1/io/BufferedInputStream.html#setProgressListener-com.codename1.io.IOProgressListener-

**Comment by kutoman** [comment]
ah thanks for the hint, I didn't know that. And sorry for the Consumer interface, I defined one in my project

**Comment by codenameone** [comment]
So do you think this PR is necessary in light of that functionality?  If not feel free to close it. If you think this is still something that should be used then you would need to make it compile ;-)

**Comment by codenameone** [comment]
Thanks!

**Pull request merged**
