### PR TITLE
Fix bug of style modifications beeing lost when hidding/unhidding a comp

### PR DESCRIPTION
**Pull request by ramsestom**
Fix this: https://github.com/codenameone/CodenameOne/issues/2764

### CODE REVIEW

**Comment by codenameone** [comment]
Why did you add two public methods that are deprecated? 
Wouldn't it make more sense to create a proper API that makes sense for the general use case instead of internal public API?
This can also pose a problem if `setHidden(true)` is invoked twice. That can happen in real life if set hidden is mapped to a UI element and the user presses it twice. It would result in hard to reproduce issues.

**Comment by ramsestom** [comment]
removed the deprecated tag but the user must be warned that unexpected results might happen when hidding/unhidding a component if he mess with this margins cache... (as long as this cache can be accessed by public methods, there is no other solution)
also calling `setHidden(true)` multiple consecutive times shouldn't be an issue anymore now

**Comment by codenameone** [comment]
I don't understand how calling `setHidden(true)` multiple times is solved here. What did I miss?

**Comment by ramsestom** [comment]
the `cacheMargins` now takes a boolean argument that, when set to false, will only erase the margins cache if this cache do not already exists. When hidding an element, this function is called with a `false` parametter. So if you hidde an element multiple times, the margin values would be cached only the first time (when they are not equals to zero exept if your element had null margins before beeing hidden of course) and restored to these values when unhidden.

**Comment by codenameone** [comment]
Thanks!

**Pull request merged**
