### PR TITLE
Tabs icon font

### PR DESCRIPTION
**Pull request by ThomasH99**

### CODE REVIEW

**Comment by ThomasH99** [comment]
Added support for custom icons to Tabs

**Comment by ThomasH99** [comment]
I hope you'll consider this PR. For now I've disabled the custom icons in my tabs, but I really need them for UI consistency :-)

**Comment by shai-almog** [comment]
Thanks!

**Comment by shai-almog** [comment]
@all-contributors please add @ThomasH99  for code

**Pull request merged**
