### PR TITLE
I did some changes to the DateFormat.java to looks more daisy

### PR DESCRIPTION
**Pull request by RishabhDixit1**

### CODE REVIEW

**Comment by shai-almog** [comment]
Can you explain the motivation behind this change?

**Comment by RishabhDixit1** [comment]
Mam/Sir..
The first of all thank you for replying!
I am a new Contributer to Open Source and Projects and I am just trying to
learn that how can be contribute.
I found this project and run on my pc and found that I can push change
without any reason?!
Well, I am Struggling to find issues and how to work on that and bugs etc.
So for my hands on experience and practice I tried this!
If you can help me please reply to guide me a good developer and Potential
Contributer.

**Comment by shai-almog** [comment]
Sure. Check out the [contributing guide](https://github.com/codenameone/CodenameOne/blob/master/CONTRIBUTING.md). 

The best way to start is with picking off a low hanging fruit. We tag issues that are easier for new contributors as "good first issue" you can see them [here](https://github.com/codenameone/CodenameOne/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

**Comment by RishabhDixit1** [comment]
Thanks a lot.

**Pull request closed without merging**
