### PR TITLE
280817 adding listener to accordion item

### PR DESCRIPTION
**Pull request by DurankGts**
adding item listener to accordion component

### CODE REVIEW

**Comment by codenameone** [comment]
Thanks.
Your listener method is misspelled (clik instead of click). 
It doesn't comply with the convention of add/remove listener that accepts an ActionListener interface which you can then implement using EventDispatcher. This is important as EventDispatcher does quite a few things such as EDT normalization etc.

**Comment by codenameone** [comment]
You also need to include JavaDoc comments for every method/class introduced.

**Comment by DurankGts** [comment]
OK, please check again my last update

**Comment by codenameone** [comment]
Thanks. 
I'll fix it to be addOnClick instead of setOnClick

**Pull request merged**
