### PR TITLE
Extend to location simulator form

### PR DESCRIPTION
**Pull request by PiotrZub**
Added velocity, altitude, direction, accuracy fields to location simulator form.
Values can be changed using mouse wheel. 
Any changes do not need update.

### CODE REVIEW

**Comment by codenameone** [comment]
@chen-fishbein please evaluate and merge if it matches your intentions for the tool

**Comment by chen-fishbein** [comment]
Nice addition, thanks!

**Comment by CraigRLang** [comment]
Are these now in the released CodeNameOne?
Or do we need to be using the source code to pick these changes up?

**Comment by codenameone** [comment]
Currently the source. We will make a release later this week probably tomorrow and every Friday from now on: https://www.codenameone.com/blog/toolbar-default-millimeter-sizes-weekly-releases.html

**Pull request merged**
