### PR TITLE
Update CodenameOne/src/com/codename1/ui/Image.java

### PR DESCRIPTION
**Pull request by ddyer0**
add a new getRGB variant
invalidate the rgb cache when it is about to be invalidated.

### CODE REVIEW

**Comment by codenameone** [comment]
Thanks

**Comment by ddyer0** [comment]
Something went wrong with the deployment of this.  It now appears in the distributed .class
files, and the getRGB(int[]) method is accepted by the build server, but when actually invoked
it gets a "no such virtual method" error.

data=[Java cpu=8.7% screen=1920x984 ppi=96 Codename1  12.81 0 The Android Project http://www.android.com/ 50.0 Linux armv7l 3.10.0] (Bitmap scanner 23 threads)in screen scanner
error is : java.lang.NoSuchMethodError: No virtual method getRGB([I)V in class Lcom/codename1/ui/Image; or its super classes (declaration of 'com.codename1.ui.Image' appears in /data/app/dev.boardspace-1/base.apk)
[Bitmap scanner] 0:0:0,0 - Exception: java.lang.NoSuchMethodError - No virtual method getRGB([I)V in class Lcom/codename1/ui/Image; or its super classes (declaration of 'com.codename1.ui.Image' appears in /data/app/dev.boardspace-1/base.apk)
java.lang.NoSuchMethodError: No virtual method getRGB([I)V in class Lcom/codename1/ui/Image; or its super classes (declaration of 'com.codename1.ui.Image' appears in /data/app/dev.boardspace-1/base.apk)
	at bridge.Platform.getRGB(Unknown Source)
	at vnc.TileManager.processImage(Unknown Source)
	at vnc.ScreenScanner.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

**Comment by ddyer0** [comment]
Still broken

**Comment by ddyer0** [comment]
Did you push another bad update and correct it ?  Yesterday my VNC application, which uses setRGB, was broken on IOS but not on Android.  I spent half the day trying to find the problem.  Today it's mysteriously fixed.

**Comment by codenameone** [comment]
No

**Pull request merged**
