### PR TITLE
Device resolution refactor

### PR DESCRIPTION
**Pull request by ramsestom**
This should fix the performances issue. 
By security I also implemented a cache for fontScale on android as I don't know if getContext().getResources().getConfiguration().fontScale is costly.
As a side effect, if a user change its prefered font scale in android accessibility parametters, he would now have to restart the app for this to be taken into account. But I don't think this is that much of a deal

### CODE REVIEW

**Comment by codenameone** [comment]
I'll try to get to it. I've got a few deadlines coming so I've got low availability this week.

**Comment by codenameone** [comment]
I just noticed from user contacts that the previous PR commented out `CN.getDeviceDPI()`. That's a HUGE problem...

**Comment by ramsestom** [comment]
you mean `getDeviceDensity()` ? If yes just uncomment it. It was commented when I removed getDeviceDensity() in Display and other methods in the first PR and I just forgot to put it back when I restored this getDeviceDensity() method as `CN.getDeviceDensity()` is not used anywhere else in the current CN1 code...

**Comment by codenameone** [comment]
You can't comment out/remove or even change the signature of a public method that's outside the impl package. That breaks binary compatibility. The new patch still has merge conflicts but it also means we'll need a deeper review of this to avoid these problems. That's generally why we prefer smaller PR's.

**Comment by ramsestom** [comment]
closing this as I am planing to split the initial PR into smaller PRs

**Pull request closed without merging**
