### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by SwingGuy1024**

### CODE REVIEW

**Comment by SwingGuy1024** [comment]
Added PreferenceListener to Preferences class.

**Comment by codenameone** [comment]
Why did you close this pull request? 
Was it by mistake?

**Comment by SwingGuy1024** [comment]
I didn't realize I had closed it. I'm new to making pull requests. Do you need me to try it again?
-- Miguel Muñoz 

    On Wednesday, December 7, 2016 9:18 PM, codenameone <notifications@github.com> wrote:
 

 Why did you close this pull request?
Was it by mistake?—

**Comment by codenameone** [comment]
No problem I got it from here...

**Comment by shai-almog** [comment]
@all-contributors please add @SwingGuy1024  for code

**Pull request merged**
