### PR TITLE
Prevent build error for  Open GL ES1.

### PR DESCRIPTION
**Pull request by PiotrZub**

### CODE REVIEW

**Comment by codenameone** [comment]
While this is easy to merge can you explain the motivation of using ES1?

We deprecated and no longer support the ES1 pipeline I've also noticed you complained about performance issues I'm assuming it relates to that pipeline.

**Comment by PiotrZub** [comment]
Of course I do not use ES1 but it still exist in your code so I make 
this this pull request.
It was my mistake when I try do build code with USE_ES2 not defined it 
take me some time to find out why error strange build errors appears :(

Sorry, performance issues is not connected with this mistake, I test it 
with USE_ES2 defined.

**Comment by shannah** [comment]
Perhaps we should just change enable the USE_ES2 constant in the source.  Currently the build server toggles this on during builds.

Re: Performance issues, please post to issue tracker and provide test case if possible.  I'll be looking into this, but it makes it much easier if you can  point me in the right direction with a test case.

**Comment by codenameone** [comment]
I think this would mask a far worse issue with graphics not working correctly so this wouldn't solve the core issue rather mask it.

**Comment by shai-almog** [comment]
@all-contributors please add @PiotrZub  for code

**Pull request closed without merging**
