### PR TITLE
Added Tabs.setSwipeOnYAxis(...) method to set the swipe on Y-Axis.

### PR DESCRIPTION
**Pull request by jsfan3**
This addition follows our discussion:
https://new.reddit.com/r/cn1/comments/quq7yo/realize_a_set_of_containers_that_are_browsable/

To test the code, you can try this example:
https://gist.github.com/jsfan3/92c8b852157c4196e11825c330641dae

The changes I've made should have no impact on the existing code, or so I think. I have followed as much as possible the logic of the pre-existing code.

For the moment, I have only tried in the Simulator.

I have seen a minor pre-existing bug; it does not depend on my modifications. It occurs only if the tabs have a margin: in such a case, for a fraction of a second, the Motion moves the incoming tab entirely to the left during the swipe (thus ignoring the margin). This bug is almost undetectable in a move along the X-axis. However, if the swipe is along the Y-axis, the bug becomes visible. It's a minor problem that I don't know how to fix; for the moment, the workaround is to have a zero margin (as in the above-linked sample code).

### CODE REVIEW

**Comment by shai-almog** [comment]
I have two small nitpicks with the code. 

The variable is swipeX while the method is swipeY. I suggest making the method swipe X and setting it to false would do what you want.

This would also fix the second problem. 

Right now you can't toggle this back and forth because of the `if` statement in that method.  By just exposing the variable this should be solved.

You would also need to add an isSwipeX method for consistency.

**Comment by jsfan3** [comment]
I made the changes you asked for and updated the javadocs.

The new sample code is: https://gist.github.com/jsfan3/67074c6684b0ee711c6f6d950cdefb57

There are two minor bugs, and I don't know how to deal with them. These two bugs don't affect my use case; however, they might affect other users.

The first one concerns the use of buttons to change tabs (so hideTabs was not invoked): the swipe effect when changing tabs happens only if the swipe is on the X-axis; otherwise, the tab change is immediate. If the developer uses hideTabs, the problem does not arise.

The second bug results from the possibility of invoking setSwipeOnXAxis as many times as you want after the Tabs component is displayed. The swipe effect does not happen correctly on the currently displayed tab, but the problem disappears at the first tab change. If the developer invokes setSwipeOnXAxis only once and before displaying Tabs, the problem does not arise.

How do you suggest proceeding?

**Comment by jsfan3** [comment]
Right now, I'm working on the two problems I listed in my last comment.

One of them I solved: basically, I forgot to use the variable "swipeOnXAxis" also inside the methods "animate()" and "setSelectedIndex(...)".

I hope to solve soon also the other problem. Then I'll send another commit when I'm all done.

**Comment by jsfan3** [comment]
I just solved the other problem as well. I forgot that the "contentPane" of Tabs changes its size and internal tab positioning when we invoke "setSwipeOnXAxis" with a different value than the current one, so that method has to call internally "revalidateLater".

Before submitting the new solving commit, I want to add a short demo video to the Javadoc.

**Comment by jsfan3** [comment]
I finished. I don't know what the failed check means.

**Comment by shai-almog** [comment]
Thanks!

**Pull request merged**
